Config Class
tmax-cloud/hypersds-provisioner pull request #12
Opened 2021-02-01 02:37 UTC by hookak

Manage ceph.conf for installing ceph cluster And
Update Configmap and Secret to Kubernetes about ceph cluster.

2021-02-01 05:23 UTC, shellwedance requested changes
Comment들에 대해서 반영 혹은 피드백 주시면 감사하겠습니다.

2021-02-01 05:23 UTC, shellwedance commented on pkg/config/wrapper.go
> +	return NewConfigFromCephCr(cr)
똑같은 함수를 두 개 만들고 wrapper에서 다른 하나를 호출하는 것보다, `configInitStruct` structure와 `NewConfigFromCephCr` 함수를 config.go 파일에 만드는 건 어떨까요?

(Node에서는 comment를 반영하여 그렇게 가져가기로 했습니다. 참고로, wrapper 파일 이름은 `node_wrapper.go` 입니다.)

2021-02-01 05:32 UTC, hookak commented on pkg/config/config.go
> +func NewConfigFromCephCr(CephCr hypersdsv1alpha1.CephClusterSpec) *CephConfig {
없습니다 수정완료

2021-02-01 05:32 UTC, hookak commented on pkg/config/config.go
> +	CrConf := make(map[string]string)
done

2021-02-01 05:33 UTC, hookak commented on pkg/config/config.go
> +func (cconf *CephConfig) ConfigFromAdm(IoUtil wrapper.IoUtilInterface, cephconf string) error {
NewConfigFromCephCr은 operator로부터 CR받아서 config class를 생성하는 생성자입니다.
ConfigFromAdm은 ceph-cluster 생성된 이후 /etc/ceph.conf를 읽는 config의 메소드입니다

2021-02-01 05:34 UTC, hookak commented on pkg/config/config.go
> +	AdmConf := make(map[string]string)
done

2021-02-01 05:35 UTC, hookak commented on pkg/config/config.go
> +	AdmSecret := make(map[string][]byte)
done

2021-02-01 05:36 UTC, hookak commented on pkg/config/config.go
> +	_, err = clientset.CoreV1().ConfigMaps("default").Get(context.TODO(), "ceph-conf", metav1.GetOptions{})
configmap은 operator쪽에서 만들고 provisioner는 update만 하기로 이야기했었습니다.
예시로 든 경우도 update가 될것 같네요

2021-02-01 05:37 UTC, hookak commented on pkg/config/config.go
> +	if err == nil {
done

2021-02-01 05:37 UTC, hookak commented on pkg/config/config.go
> +	if err == nil {
done

2021-02-01 05:56 UTC, shellwedance commented on pkg/config/config.go
> +func (cconf *CephConfig) ConfigFromAdm(IoUtil wrapper.IoUtilInterface, cephconf string) error {
> ConfigFromAdm은 ceph-cluster 생성된 이후 /etc/ceph.conf를 읽는 config의 메소드입니다

그러면 ConfigFromAdm도 /etc/ceph/ceph.conf를 읽어서 config instance를 생성하니까 기능상 생성자 함수네요.
즉, 생성자 함수가 두 개 있어야 되는 거죠.
- NewConfigFromCephCr
- NewConfigFromAdm (사실 뒤에 Adm도 정확히는 Path나 CephConf 이런 식으로 되는 게 정확하겠죠?)

왜 ConfigFromAdm은 생성자 함수가 아니라 메소드로 작성했는지 이유가 있을까요?

2021-02-01 06:00 UTC, shellwedance commented on pkg/config/config.go
> +	_, err = clientset.CoreV1().ConfigMaps("default").Get(context.TODO(), "ceph-conf", metav1.GetOptions{})
그렇다면 메소드 이름은 PutConfigToK8s가 아니라 UpdateConfigMap가 맞아보이네요.

2021-02-01 06:04 UTC, shellwedance commented on pkg/config/config.go
> +	if err == nil {
그렇다면 ceph-conf라는 ConfigMap이 존재하지 않으면 에러 상황인 거죠?
에러 상황이면 여러 처리 방법이 있겠지만 우선 panic(err) 던지고, 아니라면 update 수행하면 되겠네요

2021-02-01 06:05 UTC, hookak commented on pkg/config/config.go
> +func (cconf *CephConfig) ConfigFromAdm(IoUtil wrapper.IoUtilInterface, cephconf string) error {
음.. config instance 하나에 configFromCr, configFromAdm이 있는걸로 디자인했구요
그 이유는 나중에 하나의 ceph cluster에 한개의 config instance가 맞다고 생각했습니다

2021-02-01 06:12 UTC, hookak commented on pkg/config/wrapper.go
> +	return NewConfigFromCephCr(cr)
좋은 피드백 감사합니다! 수정했습니다

2021-02-01 06:18 UTC, hookak commented on pkg/config/config.go
> +	_, err = clientset.CoreV1().ConfigMaps("default").Get(context.TODO(), "ceph-conf", metav1.GetOptions{})
done

2021-02-01 06:18 UTC, hookak commented on pkg/config/config.go
> +func (cconf *CephConfig) PutConfigToK8s(kubeWrapper wrapper.KubeInterface) error {
done

2021-02-01 07:07 UTC, shellwedance commented on pkg/config/config.go
> +//default:default SA가 configmap put할수 있는 rolebinding 있어야함!
이 부분은 일단 default namespace와 default SA를 쓰고, 나중에 hypersds 전용 namespace와 hypersds 전용 SA를 사용하나요?

2021-02-01 07:12 UTC, hookak commented on pkg/config/config.go
> +//default:default SA가 configmap put할수 있는 rolebinding 있어야함!
네 그렇게될거같습니다

2021-02-01 07:37 UTC, shellwedance commented on pkg/config/config.go
> +func (cconf *CephConfig) ConfigFromAdm(IoUtil wrapper.IoUtilInterface, cephconf string) error {
나중에 리팩토링할 때 setter 이름을 바꾸는 걸로 하죠

2021-02-01 08:06 UTC, shellwedance approved these changes
comment 반영해주셔서 감사합니다. 디테일은 추후에 마저 고쳐나가죠.

ok-to-merge

2021-02-01 08:13 UTC, SangHyeok-Kim95 reviewed
남긴 comment에 대한 피드백 부탁드립니다.

2021-02-01 08:13 UTC, SangHyeok-Kim95 commented on pkg/config/config.go
> +func (cconf *CephConfig) ConfigFromAdm(IoUtil wrapper.IoUtilInterface, cephconf string) error {
사소한 comment입니다.
넘겨 받는 parameter의 이름을 Uppercase로 시작한 이유가 있을까요?(IoUtil)

2021-02-02 01:43 UTC, hookak commented on pkg/config/config.go
> +func (cconf *CephConfig) SetCrConf(m map[string]string) error {
cephconf의 축약이였는데 가독성을 위해 cephConf로 수정하겠습니다

2021-02-02 01:43 UTC, hookak commented on pkg/config/config.go
> +func (cconf *CephConfig) ConfigFromAdm(IoUtil wrapper.IoUtilInterface, cephconf string) error {
없습니다. done

2021-02-02 01:45 UTC, hookak commented on pkg/config/config.go
> +func (cconf *CephConfig) SetCrConf(m map[string]string) error {
cconf를 conf로 수정하겠습니다

2021-02-02 01:55 UTC, donggyupark requested changes
comment 확인 부탁드립니다.

2021-02-02 01:55 UTC, donggyupark commented on pkg/config/config.go
> +	CrConf    map[string]string
struct의 변수들이 대문자일 이유가 있을까요? 
다른 struct {node 등에서 대문자 field를 쓰는 이유는 보통 yaml 형태 생성할 때 parser가 제대로 동작하기 위해서 사용하고 있습니다.
현재 get, set method를 전부 구현하셨고, yaml로 만드는 부분이 없어서 소문자로 해도 되지 않을까요?

2021-02-02 02:27 UTC, hookak commented on pkg/config/config.go
> +	CrConf    map[string]string
맞습니다. 소문자로 변경했습니다.

2021-02-02 04:26 UTC, shellwedance approved these changes

2021-02-02 06:48 UTC, SangHyeok-Kim95 approved these changes
Comment 반영 감사합니다.

2021-02-02 06:55 UTC, merged