Update CephCluster Info to Operator
tmax-cloud/hypersds-provisioner pull request #17
Opened 2021-02-04 07:46 UTC by hookak

Update ceph.conf, keyring file to Operator after cephadm bootstrap

2021-02-04 08:17 UTC, shellwedance approved these changes
코멘트들 피드백 해주시면 감사하겠습니다.

2021-02-04 08:17 UTC, shellwedance commented on cmd/hypersds-provisioner/hypersds-provisioner.go
> +	err = cephConfig.ConfigFromAdm(common.IoUtilWrapper, "/etc/ceph/ceph.conf")
고정된 값이므로 const 변수로 쓰는 게 나을 것 같습니다.

2021-02-04 08:17 UTC, shellwedance commented on cmd/hypersds-provisioner/hypersds-provisioner.go
> +	err = cephConfig.SecretFromAdm(common.IoUtilWrapper, "/etc/ceph/ceph.client.admin.keyring")
위와 마찬가지입니다.

2021-02-04 08:17 UTC, shellwedance commented on main.go
>  		panic(err)
이 부분은 error 발생 시 error 종류에 맞는 Exit code가 return되나요?

2021-02-04 08:35 UTC, shellwedance commented on cmd/hypersds-provisioner/hypersds-provisioner.go
> +func UpdateCephClusterToOp() error {
외부에 export할 일이 있나요?

2021-02-04 08:36 UTC, hookak commented on cmd/hypersds-provisioner/hypersds-provisioner.go
> +	err = cephConfig.ConfigFromAdm(common.IoUtilWrapper, "/etc/ceph/ceph.conf")
done

2021-02-04 08:37 UTC, hookak commented on cmd/hypersds-provisioner/hypersds-provisioner.go
> +func UpdateCephClusterToOp() error {
없습니다

2021-02-04 08:38 UTC, shellwedance requested changes

2021-02-04 08:38 UTC, shellwedance commented on cmd/hypersds-provisioner/hypersds-provisioner.go
> +	err = cephConfig.ConfigFromAdm(common.IoUtilWrapper, "/etc/ceph/ceph.conf")
Deploy node의 /etc/ceph/ceph.conf 파일을 container로 복사 또는 내용 copy해오는 logic이 없네요

2021-02-04 08:38 UTC, hookak commented on main.go
>  		panic(err)
이부분은 태욱님이 구현하신거아닌가요? panic(err)하면 exit status에 error code가 남습니다
제가 os.Exit(0)로 명시했는데 이렇게 안해도 정상적으로 종료되면 exit 0 로 return 되긴하네요

2021-02-04 08:40 UTC, shellwedance commented on cmd/hypersds-provisioner/hypersds-provisioner.go
> +	err = cephConfig.ConfigFromAdm(common.IoUtilWrapper, "/etc/ceph/ceph.conf")
해당 부분이 Node의 method에 다른 node로부터 container로 가져올 수 있도록 추가 구현해야겠네요.
현재는 container에서 다른 Node로 scp하는 기능만 구현되어 있습니다.

2021-02-04 08:43 UTC, hookak commented on cmd/hypersds-provisioner/hypersds-provisioner.go
> +	err = cephConfig.SecretFromAdm(common.IoUtilWrapper, "/etc/ceph/ceph.client.admin.keyring")
done

2021-02-04 08:44 UTC, hookak commented on cmd/hypersds-provisioner/hypersds-provisioner.go
> +	err = cephConfig.ConfigFromAdm(common.IoUtilWrapper, "/etc/ceph/ceph.conf")
네 맞습니다.. 피드백감사해요 그부분 태욱님이 추가부탁드립니다

2021-02-04 13:28 UTC, shellwedance commented on cmd/hypersds-provisioner/hypersds-provisioner.go
> +	err = cephConfig.ConfigFromAdm(common.IoUtilWrapper, "/etc/ceph/ceph.conf")
추가 완료했습니다.

2021-02-04 13:30 UTC, shellwedance commented on main.go
>  		panic(err)
아 그러면 os.Exit을 둘 다 적용하던가 기존대로 가면 되겠네요.

2021-02-04 13:37 UTC, shellwedance approved these changes
works it for me

2021-02-05 01:56 UTC, SangHyeok-Kim95 requested changes
피드백 반영 부탁드립니다.

2021-02-05 01:56 UTC, SangHyeok-Kim95 commented on cmd/hypersds-provisioner/hypersds-provisioner.go
> +	//err = processCmdOnNode(targetNode, admBootstrapCmd)
사용하지 않는 코드는 제거하는 것이 좋을 것 같습니다.

2021-02-05 01:58 UTC, shellwedance commented on cmd/hypersds-provisioner/hypersds-provisioner.go
> +	//err = processCmdOnNode(targetNode, admBootstrapCmd)
reflected

2021-02-05 01:59 UTC, SangHyeok-Kim95 approved these changes
LGTM

2021-02-05 02:18 UTC, donggyupark reviewed
피드백 반영부탁드립니다.

2021-02-05 02:18 UTC, donggyupark commented on pkg/node/const.go
> +	SRC Role = iota
SRC 보다는 SOURCE가 낫지 않을까요?

2021-02-05 02:18 UTC, donggyupark commented on cmd/hypersds-provisioner/hypersds-provisioner.go
> +func processExecError(errExec error, output bytes.Buffer) error {
해당 함수의 위치는 util package가 더 맞아보이네요

2021-02-05 02:18 UTC, donggyupark commented on pkg/node/const.go
> +	SRC Role = iota
SRC보다는 SOURCE가 더 낫지 않을까요?

2021-02-05 02:21 UTC, shellwedance commented on pkg/node/const.go
> +	SRC Role = iota
SRC라 하면 소스 코드 같아보이기 때문인가요?

2021-02-05 02:38 UTC, donggyupark commented on pkg/node/const.go
> +	SRC Role = iota
음 제가 봤을 때는 헷갈렸습니다. 사실 const 변수 name은 줄이지 않는 방향으로 가는 것이 맞지 않나 싶기도 하고요

2021-02-05 03:04 UTC, shellwedance commented on cmd/hypersds-provisioner/hypersds-provisioner.go
> +	pathConfFromCr      = "/ceph_initial.conf"
좋은 의견입니다. 다만 입력받는 파일과 작업 수행을 위해 생성하는 파일 경로는 다르게 가져가는 것이 좋아보입니다.
- `/manifest` directory에 operator로부터 입력받는 파일(ex. cluster.yaml) 위치
- `/working/` directory에 각 class마다 directory를 만들고 작업을 위해 생성하는 파일 만들기
  - ex. CephCluster CR로부터 생성한 ceph.conf의 경로 : `/working/config/ceph_initial.conf`

@donggyupark @SangHyeok-Kim95 @hookak 위 내용에 찬성하시면 반영하겠습니다.

2021-02-05 03:05 UTC, shellwedance commented on cmd/hypersds-provisioner/hypersds-provisioner.go
> +func processExecError(errExec error, output bytes.Buffer) error {
좋은 의견입니다. Exec과 관련된 내용인데, 해당 내용은 issue 등록 후 추후 반영하죠.

2021-02-05 06:38 UTC, donggyupark approved these changes
LGTM

2021-02-05 06:41 UTC, merged