Add registry dockerfile
tmax-cloud/hypersds-provisioner pull request #35
Opened 2021-03-11 08:59 UTC by shellwedance

- modify CI scripts to support Docker Private Registry (DPR)
- modify e2e tests to support DPR
- modify action to input DPR secrets (endpoint, ID, pw)
- add action failure handler

2021-03-12 05:00 UTC, donggyupark requested changes

2021-03-12 05:00 UTC, donggyupark commented on tests/e2e/bootstrap_test.go
> +	inputDirName  = "inputs/"
cluster.yaml은 절대경로 /e2e/inputs/cluster.yaml 을 명시해주면서 bootstrap.yaml은 inputs/bootstrap.yaml 로 상대 파일 경로를 나타내는 것이 이해가 되지 않습니다. 둘 중 하나로 통일하는 것이 좋을 것 같습니다.

2021-03-15 09:52 UTC, shellwedance commented on tests/e2e/bootstrap_test.go
> +	inputDirName  = "inputs/"
`./tests/e2e/util.go`에서 provisioner pod을 띄울 때 볼륨으로 붙여주는 경로는 minikube VM의 경로입니다. (CI 파이프라인에서 minikube VM을 띄울 때 VM의 `/e2e` 디렉토리에 host의 `hypersds-provisioner/tests/e2e` 디렉토리를 마운트합니다)

`./tests/e2e/bootstrap.go`에서 bootstrap에 필요한 input yaml 파일을 parsing하는 프로세스는 host에서 도는 프로세스입니다. (host가 minikube VM의 kubeconfig를 가지고 있으면서 parsing한 값들로부터 pod 및 configmap, secret, role, rolebinding 등을 띄움)

그래서 현재 minikube VM의 경로는 절대경로로 들어가있고, host의 경로는 해당 suite의 위치로부터의 상대 경로로 구현되어 있습니다.

그러면 host의 `hypersds-provisioner/tests/inputs/bootstrap.yaml` 경로를 절대경로로 구하도록 수정할까요?

2021-03-16 05:32 UTC, shellwedance commented on tests/e2e/bootstrap_test.go
> +	inputDirName  = "inputs/"
- `util.go`의 const는 pod name, pod mountPath 등 pod 관련된 것만 남기고 나머지 필요한 값들은 parameter로 옮겨서 다른 e2e test들에서 직접 입력하도록 바꿨습니다.
- `cluster.yaml` 파일이 있는 host path를 `./tests/e2e/inputs/manifest/` 디렉토리로 바꿨습니다. 
  - 만약 host가 아닌 vm에서 pod을 수행시킨다면, 해당 경로를 input 파일에 입력하면 그 경로로 host path를 `util.go`에 전달하도록 구현했습니다.

2021-03-16 05:32 UTC, donggyupark approved these changes

2021-03-16 05:33 UTC, merged