Add Ceph spec read logic
tmax-cloud/hypersds-provisioner pull request #9
Opened 2021-01-27 08:36 UTC by SangHyeok-Kim95

- Add Ceph spec read logic
- Add simple unit test code for Ceph spec read logic

2021-01-28 02:18 UTC, shellwedance requested changes
go.mod 코멘트만 반영하면 merge 가능할 듯합니다.

2021-01-28 02:18 UTC, shellwedance commented on main.go
>  func main() {
main logic 구현부는 cmd/hypersds-provisioner 에서 구현하는 게 어떨까요?

2021-01-28 02:18 UTC, shellwedance commented on go.mod
> +	github.com/tmax-cloud/hypersds-operator v0.0.0-20210121014745-795b7a2a1c24
`hypersds-operator`의 특정 브랜치(create-cm)를 이용하는데, 해당 module은 그 브랜치의 모듈이 아니어 보입니다.

go.mod에 `hypersds-operator`를 명시하지 말고, 일단은 각자의 환경에서 create-cm 브랜치를 직접 go get 해서 쓰는 것을 제안합니다.

2021-01-28 02:19 UTC, shellwedance commented on go.mod
> +	github.com/tmax-cloud/hypersds-operator v0.0.0-20210121014745-795b7a2a1c24
나중에는 개발자 간의 모듈 통일을 위해 추가해야겠지만, 현재의 간단한 방법은 go.mod와 go.sum을 git add 하지 않는 겁니다.

2021-01-28 09:31 UTC, hookak approved these changes
lgtm

2021-01-29 01:34 UTC, SangHyeok-Kim95 commented on main.go
>  func main() {
좋은 의견입니다. 한번 고려해 보겠습니다.

2021-01-29 01:38 UTC, SangHyeok-Kim95 commented on go.mod
> +	github.com/tmax-cloud/hypersds-operator v0.0.0-20210121014745-795b7a2a1c24
개발 기록을 남기기 위해서 작성합니다. 회의 결과 repo의 ci/cd pipeline 통과를 위해서, go.mod을 수정하여 hypersds-operator의 create-cm branch를 사용하는 것으로 결정되었습니다. 해당 사항 반영했습니다. 확인 부탁드립니다.

2021-01-29 06:56 UTC, donggyupark approved these changes
lgtm

2021-01-29 08:22 UTC, shellwedance approved these changes
LGTM

2021-01-29 08:22 UTC, merged